/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.records;


import minvakt.datamodel.tables.DepartmentRequiredPerShift;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "department_required_per_shift", schema = "g_scrum03")
public class DepartmentRequiredPerShiftRecord extends UpdatableRecordImpl<DepartmentRequiredPerShiftRecord> implements Record4<Integer, Short, Integer, Short> {

    private static final long serialVersionUID = -70697527;

    /**
     * Setter for <code>g_scrum03.department_required_per_shift.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_per_shift.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>g_scrum03.department_required_per_shift.department_id</code>.
     */
    public void setDepartmentId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_per_shift.department_id</code>.
     */
    @Column(name = "department_id", nullable = false, precision = 5)
    public Short getDepartmentId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>g_scrum03.department_required_per_shift.shift_id</code>.
     */
    public void setShiftId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_per_shift.shift_id</code>.
     */
    @Column(name = "shift_id", nullable = false, precision = 10)
    public Integer getShiftId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>g_scrum03.department_required_per_shift.amount</code>.
     */
    public void setAmount(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_per_shift.amount</code>.
     */
    @Column(name = "amount", nullable = false, precision = 5)
    public Short getAmount() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Short, Integer, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Short, Integer, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DepartmentRequiredPerShift.DEPARTMENT_REQUIRED_PER_SHIFT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return DepartmentRequiredPerShift.DEPARTMENT_REQUIRED_PER_SHIFT.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DepartmentRequiredPerShift.DEPARTMENT_REQUIRED_PER_SHIFT.SHIFT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return DepartmentRequiredPerShift.DEPARTMENT_REQUIRED_PER_SHIFT.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getShiftId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredPerShiftRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredPerShiftRecord value2(Short value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredPerShiftRecord value3(Integer value) {
        setShiftId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredPerShiftRecord value4(Short value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredPerShiftRecord values(Integer value1, Short value2, Integer value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DepartmentRequiredPerShiftRecord
     */
    public DepartmentRequiredPerShiftRecord() {
        super(DepartmentRequiredPerShift.DEPARTMENT_REQUIRED_PER_SHIFT);
    }

    /**
     * Create a detached, initialised DepartmentRequiredPerShiftRecord
     */
    public DepartmentRequiredPerShiftRecord(Integer id, Short departmentId, Integer shiftId, Short amount) {
        super(DepartmentRequiredPerShift.DEPARTMENT_REQUIRED_PER_SHIFT);

        set(0, id);
        set(1, departmentId);
        set(2, shiftId);
        set(3, amount);
    }
}
