/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.records;


import minvakt.datamodel.tables.DepartmentRequiredEmployeesPerCategory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "department_required_employees_per_category", schema = "g_scrum03")
public class DepartmentRequiredEmployeesPerCategoryRecord extends UpdatableRecordImpl<DepartmentRequiredEmployeesPerCategoryRecord> implements Record4<Integer, Short, Short, Short> {

    private static final long serialVersionUID = -251652793;

    /**
     * Setter for <code>g_scrum03.department_required_employees_per_category.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_employees_per_category.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>g_scrum03.department_required_employees_per_category.department_id</code>.
     */
    public void setDepartmentId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_employees_per_category.department_id</code>.
     */
    @Column(name = "department_id", nullable = false, precision = 5)
    public Short getDepartmentId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>g_scrum03.department_required_employees_per_category.category_id</code>.
     */
    public void setCategoryId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_employees_per_category.category_id</code>.
     */
    @Column(name = "category_id", nullable = false, precision = 5)
    public Short getCategoryId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>g_scrum03.department_required_employees_per_category.amount</code>.
     */
    public void setAmount(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>g_scrum03.department_required_employees_per_category.amount</code>.
     */
    @Column(name = "amount", nullable = false, precision = 5)
    public Short getAmount() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Short, Short, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Short, Short, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DepartmentRequiredEmployeesPerCategory.DEPARTMENT_REQUIRED_EMPLOYEES_PER_CATEGORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return DepartmentRequiredEmployeesPerCategory.DEPARTMENT_REQUIRED_EMPLOYEES_PER_CATEGORY.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return DepartmentRequiredEmployeesPerCategory.DEPARTMENT_REQUIRED_EMPLOYEES_PER_CATEGORY.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return DepartmentRequiredEmployeesPerCategory.DEPARTMENT_REQUIRED_EMPLOYEES_PER_CATEGORY.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredEmployeesPerCategoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredEmployeesPerCategoryRecord value2(Short value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredEmployeesPerCategoryRecord value3(Short value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredEmployeesPerCategoryRecord value4(Short value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DepartmentRequiredEmployeesPerCategoryRecord values(Integer value1, Short value2, Short value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DepartmentRequiredEmployeesPerCategoryRecord
     */
    public DepartmentRequiredEmployeesPerCategoryRecord() {
        super(DepartmentRequiredEmployeesPerCategory.DEPARTMENT_REQUIRED_EMPLOYEES_PER_CATEGORY);
    }

    /**
     * Create a detached, initialised DepartmentRequiredEmployeesPerCategoryRecord
     */
    public DepartmentRequiredEmployeesPerCategoryRecord(Integer id, Short departmentId, Short categoryId, Short amount) {
        super(DepartmentRequiredEmployeesPerCategory.DEPARTMENT_REQUIRED_EMPLOYEES_PER_CATEGORY);

        set(0, id);
        set(1, departmentId);
        set(2, categoryId);
        set(3, amount);
    }
}
