/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import minvakt.datamodel.tables.EmployeeTimeWorkedWeek;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Table(name = "employee_time_worked_week", schema = "g_scrum03")
public class EmployeeTimeWorkedWeekRecord extends TableRecordImpl<EmployeeTimeWorkedWeekRecord> implements Record4<Integer, Short, String, Integer> {

    private static final long serialVersionUID = 818444241;

    /**
     * Setter for <code>g_scrum03.employee_time_worked_week.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_time_worked_week.employee_id</code>.
     */
    @Column(name = "employee_id", nullable = false, precision = 10)
    public Integer getEmployeeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>g_scrum03.employee_time_worked_week.position_percentage</code>.
     */
    public void setPositionPercentage(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_time_worked_week.position_percentage</code>.
     */
    @Column(name = "position_percentage", nullable = false, precision = 5)
    public Short getPositionPercentage() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>g_scrum03.employee_time_worked_week.time_worked</code>.
     */
    public void setTimeWorked(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_time_worked_week.time_worked</code>.
     */
    @Column(name = "time_worked", length = 10)
    public String getTimeWorked() {
        return (String) get(2);
    }

    /**
     * Setter for <code>g_scrum03.employee_time_worked_week.week_num</code>.
     */
    public void setWeekNum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_time_worked_week.week_num</code>.
     */
    @Column(name = "week_num", precision = 10)
    public Integer getWeekNum() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Short, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Short, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EmployeeTimeWorkedWeek.EMPLOYEE_TIME_WORKED_WEEK.EMPLOYEE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return EmployeeTimeWorkedWeek.EMPLOYEE_TIME_WORKED_WEEK.POSITION_PERCENTAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EmployeeTimeWorkedWeek.EMPLOYEE_TIME_WORKED_WEEK.TIME_WORKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return EmployeeTimeWorkedWeek.EMPLOYEE_TIME_WORKED_WEEK.WEEK_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getPositionPercentage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTimeWorked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getWeekNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeTimeWorkedWeekRecord value1(Integer value) {
        setEmployeeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeTimeWorkedWeekRecord value2(Short value) {
        setPositionPercentage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeTimeWorkedWeekRecord value3(String value) {
        setTimeWorked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeTimeWorkedWeekRecord value4(Integer value) {
        setWeekNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeTimeWorkedWeekRecord values(Integer value1, Short value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeTimeWorkedWeekRecord
     */
    public EmployeeTimeWorkedWeekRecord() {
        super(EmployeeTimeWorkedWeek.EMPLOYEE_TIME_WORKED_WEEK);
    }

    /**
     * Create a detached, initialised EmployeeTimeWorkedWeekRecord
     */
    public EmployeeTimeWorkedWeekRecord(Integer employeeId, Short positionPercentage, String timeWorked, Integer weekNum) {
        super(EmployeeTimeWorkedWeek.EMPLOYEE_TIME_WORKED_WEEK);

        set(0, employeeId);
        set(1, positionPercentage);
        set(2, timeWorked);
        set(3, weekNum);
    }
}
