/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.records;


import minvakt.datamodel.tables.EmployeeCategory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "employee_category", schema = "g_scrum03")
public class EmployeeCategoryRecord extends UpdatableRecordImpl<EmployeeCategoryRecord> implements Record5<Short, String, Boolean, Short, Boolean> {

    private static final long serialVersionUID = -288527588;

    /**
     * Setter for <code>g_scrum03.employee_category.category_id</code>.
     */
    public void setCategoryId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_category.category_id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "category_id", unique = true, nullable = false, precision = 5)
    public Short getCategoryId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>g_scrum03.employee_category.category_name</code>.
     */
    public void setCategoryName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_category.category_name</code>.
     */
    @Column(name = "category_name", nullable = false, length = 30)
    public String getCategoryName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>g_scrum03.employee_category.admin</code>.
     */
    public void setAdmin(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_category.admin</code>.
     */
    @Column(name = "admin")
    public Boolean getAdmin() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>g_scrum03.employee_category.required_per_shift</code>.
     */
    public void setRequiredPerShift(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_category.required_per_shift</code>.
     */
    @Column(name = "required_per_shift", precision = 5)
    public Short getRequiredPerShift() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>g_scrum03.employee_category.available_for_shifts</code>.
     */
    public void setAvailableForShifts(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>g_scrum03.employee_category.available_for_shifts</code>.
     */
    @Column(name = "available_for_shifts")
    public Boolean getAvailableForShifts() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Short, String, Boolean, Short, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Short, String, Boolean, Short, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return EmployeeCategory.EMPLOYEE_CATEGORY.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EmployeeCategory.EMPLOYEE_CATEGORY.CATEGORY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return EmployeeCategory.EMPLOYEE_CATEGORY.ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return EmployeeCategory.EMPLOYEE_CATEGORY.REQUIRED_PER_SHIFT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return EmployeeCategory.EMPLOYEE_CATEGORY.AVAILABLE_FOR_SHIFTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategoryName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getRequiredPerShift();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getAvailableForShifts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeCategoryRecord value1(Short value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeCategoryRecord value2(String value) {
        setCategoryName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeCategoryRecord value3(Boolean value) {
        setAdmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeCategoryRecord value4(Short value) {
        setRequiredPerShift(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeCategoryRecord value5(Boolean value) {
        setAvailableForShifts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeCategoryRecord values(Short value1, String value2, Boolean value3, Short value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeCategoryRecord
     */
    public EmployeeCategoryRecord() {
        super(EmployeeCategory.EMPLOYEE_CATEGORY);
    }

    /**
     * Create a detached, initialised EmployeeCategoryRecord
     */
    public EmployeeCategoryRecord(Short categoryId, String categoryName, Boolean admin, Short requiredPerShift, Boolean availableForShifts) {
        super(EmployeeCategory.EMPLOYEE_CATEGORY);

        set(0, categoryId);
        set(1, categoryName);
        set(2, admin);
        set(3, requiredPerShift);
        set(4, availableForShifts);
    }
}
