/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables;


import java.time.LocalDate;

import javax.annotation.Generated;

import minvakt.datamodel.GScrum03;
import minvakt.datamodel.tables.records.EmployeeTimeWorkedWeekRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeTimeWorkedWeek extends TableImpl<EmployeeTimeWorkedWeekRecord> {

    private static final long serialVersionUID = -2021554601;

    /**
     * The reference instance of <code>g_scrum03.employee_time_worked_week</code>
     */
    public static final EmployeeTimeWorkedWeek EMPLOYEE_TIME_WORKED_WEEK = new EmployeeTimeWorkedWeek();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeeTimeWorkedWeekRecord> getRecordType() {
        return EmployeeTimeWorkedWeekRecord.class;
    }

    /**
     * The column <code>g_scrum03.employee_time_worked_week.employee_id</code>.
     */
    public final TableField<EmployeeTimeWorkedWeekRecord, Integer> EMPLOYEE_ID = createField("employee_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>g_scrum03.employee_time_worked_week.position_percentage</code>.
     */
    public final TableField<EmployeeTimeWorkedWeekRecord, Short> POSITION_PERCENTAGE = createField("position_percentage", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>g_scrum03.employee_time_worked_week.time_worked</code>.
     */
    public final TableField<EmployeeTimeWorkedWeekRecord, String> TIME_WORKED = createField("time_worked", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>g_scrum03.employee_time_worked_week.start_of_week</code>.
     */
    public final TableField<EmployeeTimeWorkedWeekRecord, LocalDate> START_OF_WEEK = createField("start_of_week", org.jooq.impl.SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>g_scrum03.employee_time_worked_week.year_field</code>.
     */
    public final TableField<EmployeeTimeWorkedWeekRecord, Integer> YEAR_FIELD = createField("year_field", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>g_scrum03.employee_time_worked_week.week_num</code>.
     */
    public final TableField<EmployeeTimeWorkedWeekRecord, Integer> WEEK_NUM = createField("week_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>g_scrum03.employee_time_worked_week</code> table reference
     */
    public EmployeeTimeWorkedWeek() {
        this("employee_time_worked_week", null);
    }

    /**
     * Create an aliased <code>g_scrum03.employee_time_worked_week</code> table reference
     */
    public EmployeeTimeWorkedWeek(String alias) {
        this(alias, EMPLOYEE_TIME_WORKED_WEEK);
    }

    private EmployeeTimeWorkedWeek(String alias, Table<EmployeeTimeWorkedWeekRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmployeeTimeWorkedWeek(String alias, Table<EmployeeTimeWorkedWeekRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return GScrum03.G_SCRUM03;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeTimeWorkedWeek as(String alias) {
        return new EmployeeTimeWorkedWeek(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeeTimeWorkedWeek rename(String name) {
        return new EmployeeTimeWorkedWeek(name, null);
    }
}
