/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.*;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "department_required_employees_per_category", schema = "g_scrum03")
public class DepartmentRequiredEmployeesPerCategory implements Serializable {

    private static final long serialVersionUID = -615314058;

    private Integer id;
    private Short   departmentId;
    private Short   categoryId;
    private Short   amount;

    public DepartmentRequiredEmployeesPerCategory() {}

    public DepartmentRequiredEmployeesPerCategory(DepartmentRequiredEmployeesPerCategory value) {
        this.id = value.id;
        this.departmentId = value.departmentId;
        this.categoryId = value.categoryId;
        this.amount = value.amount;
    }

    public DepartmentRequiredEmployeesPerCategory(
        Integer id,
        Short   departmentId,
        Short   categoryId,
        Short   amount
    ) {
        this.id = id;
        this.departmentId = departmentId;
        this.categoryId = categoryId;
        this.amount = amount;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "department_id", nullable = false, precision = 5)
    public Short getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Short departmentId) {
        this.departmentId = departmentId;
    }

    @Column(name = "category_id", nullable = false, precision = 5)
    public Short getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Short categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "amount", nullable = false, precision = 5)
    public Short getAmount() {
        return this.amount;
    }

    public void setAmount(Short amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DepartmentRequiredEmployeesPerCategory (");

        sb.append(id);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
