/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.*;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "department_required_employees_per_category", schema = "g_scrum03")
public class DepartmentRequiredEmployeesPerCategory implements Serializable {

    private static final long serialVersionUID = -1646818370;

    private Integer id;
    private Integer departmentId;
    private Integer categoryId;
    private Integer amount;

    public DepartmentRequiredEmployeesPerCategory() {
    }

    public DepartmentRequiredEmployeesPerCategory(DepartmentRequiredEmployeesPerCategory value) {
        this.id = value.id;
        this.departmentId = value.departmentId;
        this.categoryId = value.categoryId;
        this.amount = value.amount;
    }

    public DepartmentRequiredEmployeesPerCategory(
            Integer id,
            Integer departmentId,
            Integer categoryId,
            Integer amount
    ) {
        this.id = id;
        this.departmentId = departmentId;
        this.categoryId = categoryId;
        this.amount = amount;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "department_id", nullable = false, precision = 10)
    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @Column(name = "category_id", nullable = false, precision = 10)
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "amount", nullable = false, precision = 7)
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DepartmentRequiredEmployeesPerCategory (");

        sb.append(id);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
