/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.pojos;


import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.annotation.Generated;
import javax.persistence.*;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "employee", schema = "g_scrum03")
public class Employee implements Serializable {

    private static final long serialVersionUID = -250030484;

    private Integer employeeId;
    private Short   categoryId;
    private String  firstName;
    private String  lastName;
    private Integer phone;
    private String  email;
    private Short   positionPercentage;
    @JsonIgnore
    private String  passwd;
    @JsonIgnore
    private Boolean enabled;
    @JsonIgnore
    private Boolean changePwOnLogon;

    public Employee() {}

    public Employee(Employee value) {
        this.employeeId = value.employeeId;
        this.categoryId = value.categoryId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.phone = value.phone;
        this.email = value.email;
        this.positionPercentage = value.positionPercentage;
        this.passwd = value.passwd;
        this.enabled = value.enabled;
        this.changePwOnLogon = value.changePwOnLogon;
    }

    public Employee(
        Integer employeeId,
        Short   categoryId,
        String  firstName,
        String  lastName,
        Integer phone,
        String  email,
        Short   positionPercentage,
        String  passwd,
        Boolean enabled,
        Boolean changePwOnLogon
    ) {
        this.employeeId = employeeId;
        this.categoryId = categoryId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.positionPercentage = positionPercentage;
        this.passwd = passwd;
        this.enabled = enabled;
        this.changePwOnLogon = changePwOnLogon;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "employee_id", unique = true, nullable = false, precision = 10)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name = "category_id", nullable = false, precision = 5)
    public Short getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Short categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "first_name", nullable = false, length = 30)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", nullable = false, length = 30)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "phone", nullable = false, precision = 10)
    public Integer getPhone() {
        return this.phone;
    }

    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    @Column(name = "email", unique = true, nullable = false, length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "position_percentage", nullable = false, precision = 5)
    public Short getPositionPercentage() {
        return this.positionPercentage;
    }

    public void setPositionPercentage(Short positionPercentage) {
        this.positionPercentage = positionPercentage;
    }

    @Column(name = "passwd", length = 60)
    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    @Column(name = "enabled")
    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Column(name = "change_pw_on_logon", nullable = false)
    public Boolean getChangePwOnLogon() {
        return this.changePwOnLogon;
    }

    public void setChangePwOnLogon(Boolean changePwOnLogon) {
        this.changePwOnLogon = changePwOnLogon;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employee (");

        sb.append(employeeId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(positionPercentage);
        sb.append(", ").append(passwd);
        sb.append(", ").append(enabled);
        sb.append(", ").append(changePwOnLogon);

        sb.append(")");
        return sb.toString();
    }
}
