/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Table(name = "employee_time_worked_week", schema = "g_scrum03")
public class EmployeeTimeWorkedWeek implements Serializable {

    private static final long serialVersionUID = 318106537;

    private Integer   employeeId;
    private Short     positionPercentage;
    private String    timeWorked;
    private LocalDate startOfWeek;
    private Integer   yearField;
    private Integer   weekNum;

    public EmployeeTimeWorkedWeek() {}

    public EmployeeTimeWorkedWeek(EmployeeTimeWorkedWeek value) {
        this.employeeId = value.employeeId;
        this.positionPercentage = value.positionPercentage;
        this.timeWorked = value.timeWorked;
        this.startOfWeek = value.startOfWeek;
        this.yearField = value.yearField;
        this.weekNum = value.weekNum;
    }

    public EmployeeTimeWorkedWeek(
        Integer   employeeId,
        Short     positionPercentage,
        String    timeWorked,
        LocalDate startOfWeek,
        Integer   yearField,
        Integer   weekNum
    ) {
        this.employeeId = employeeId;
        this.positionPercentage = positionPercentage;
        this.timeWorked = timeWorked;
        this.startOfWeek = startOfWeek;
        this.yearField = yearField;
        this.weekNum = weekNum;
    }

    @Column(name = "employee_id", nullable = false, precision = 10)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name = "position_percentage", nullable = false, precision = 5)
    public Short getPositionPercentage() {
        return this.positionPercentage;
    }

    public void setPositionPercentage(Short positionPercentage) {
        this.positionPercentage = positionPercentage;
    }

    @Column(name = "time_worked", length = 10)
    public String getTimeWorked() {
        return this.timeWorked;
    }

    public void setTimeWorked(String timeWorked) {
        this.timeWorked = timeWorked;
    }

    @Column(name = "start_of_week")
    public LocalDate getStartOfWeek() {
        return this.startOfWeek;
    }

    public void setStartOfWeek(LocalDate startOfWeek) {
        this.startOfWeek = startOfWeek;
    }

    @Column(name = "year_field", precision = 10)
    public Integer getYearField() {
        return this.yearField;
    }

    public void setYearField(Integer yearField) {
        this.yearField = yearField;
    }

    @Column(name = "week_num", precision = 10)
    public Integer getWeekNum() {
        return this.weekNum;
    }

    public void setWeekNum(Integer weekNum) {
        this.weekNum = weekNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EmployeeTimeWorkedWeek (");

        sb.append(employeeId);
        sb.append(", ").append(positionPercentage);
        sb.append(", ").append(timeWorked);
        sb.append(", ").append(startOfWeek);
        sb.append(", ").append(yearField);
        sb.append(", ").append(weekNum);

        sb.append(")");
        return sb.toString();
    }
}
