/*
 * This file is generated by jOOQ.
*/
package minvakt.datamodel.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.*;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "shift_assignment", schema = "g_scrum03")
public class ShiftAssignment implements Serializable {

    private static final long serialVersionUID = 184209016;

    private Integer id;
    private Integer shiftId;
    private Integer employeeId;
    private Boolean absent;
    private String commentForAbsence;

    public ShiftAssignment() {
    }

    public ShiftAssignment(ShiftAssignment value) {
        this.id = value.id;
        this.shiftId = value.shiftId;
        this.employeeId = value.employeeId;
        this.absent = value.absent;
        this.commentForAbsence = value.commentForAbsence;
    }

    public ShiftAssignment(
            Integer id,
            Integer shiftId,
            Integer employeeId,
            Boolean absent,
            String commentForAbsence
    ) {
        this.id = id;
        this.shiftId = shiftId;
        this.employeeId = employeeId;
        this.absent = absent;
        this.commentForAbsence = commentForAbsence;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "shift_id", nullable = false, precision = 10)
    public Integer getShiftId() {
        return this.shiftId;
    }

    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    @Column(name = "employee_id", nullable = false, precision = 10)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name = "absent", nullable = false)
    public Boolean getAbsent() {
        return this.absent;
    }

    public void setAbsent(Boolean absent) {
        this.absent = absent;
    }

    @Column(name = "comment_for_absence", length = 100)
    public String getCommentForAbsence() {
        return this.commentForAbsence;
    }

    public void setCommentForAbsence(String commentForAbsence) {
        this.commentForAbsence = commentForAbsence;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShiftAssignment (");

        sb.append(id);
        sb.append(", ").append(shiftId);
        sb.append(", ").append(employeeId);
        sb.append(", ").append(absent);
        sb.append(", ").append(commentForAbsence);

        sb.append(")");
        return sb.toString();
    }
}
