spring:
  datasource:
    url: jdbc:mysql://mysql.stud.iie.ntnu.no/g_scrum03
    username: g_scrum03
    password: Xc3e3V5A
    driver-class-name: com.mysql.jdbc.Driver
    tomcat.max-active: 3
    tomcat.initial-size: 1
    tomcat.min-idle: 1
    tomcat.max-idle: 2
  jpa:
    hibernate.ddl-auto: validate
logging:
  level:
    org:
      hibernate: WARN
      springframework: WARN
server:
  port: ${port:8080}
---

spring:
  profiles:
    active: dev
#  datasource:
#    url: jdbc:h2:~/test
logging:
  level:
    org:
      hibernate: INFO
      springframework: INFO
---

spring:
  profiles: production
  datasource:
    tomcat:
      max-active: 10
      initial-size: 3
      min-idle: 2
      max-idle: 6
logging:
  level:
    org:
      hibernate: WARN
      springframework: WARN
      apache: WARN
    minvakt: WARN
