spring:
  datasource:
    url: jdbc:mysql://mysql.stud.iie.ntnu.no/g_scrum03
    username: g_scrum03
    password: Xc3e3V5A
    driver-class-name: com.mysql.jdbc.Driver
    tomcat.max-active: 3
    tomcat.initial-size: 1
    tomcat.min-idle: 1
    tomcat.max-idle: 2
  jpa:
    hibernate.ddl-auto: validate
logging:
  level:
    org:
      hibernate: WARN
      springframework: WARN